services:
  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: runner
    ports:
      - 3000:3000
    platform: linux/amd64
    env_file: .docker.env
    environment:
      VIRTUAL_HOST: local.nexolabs.dev
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: /
      PUBLIC_AUTH_KEYCLOAK_ISSUER: https://auth.nexolabs.xyz/realms/Escohotado
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - outside

  cms:
    container_name: cms
    restart: always
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: runner
    ports:
      - 3001:3000
    platform: linux/amd64
    env_file: .docker.env
    environment:
      VIRTUAL_HOST: local.nexolabs.dev
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: ~^/(api|admin)
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - outside

  postgres:
    container_name: escota_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=devsecret
      - POSTGRES_USER=admin
      - POSTGRES_DB=escota_web
    networks:
      - outside
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - outside

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    env_file:
    - .docker.env
    restart: unless-stopped
    networks:
      - outside

volumes:
  conf:
  html:
  vhost:

networks:
  outside:
