services:
  cms:
    container_name: cms
    restart: always
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: runner
    ports:
      - 3000:3000
    platform: linux/amd64
    env_file: .docker.env
    environment:
      VIRTUAL_HOST: local.nexolabs.dev
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: ~^/(api|admin|media|_next)
    depends_on:
      - escota_db
    networks:
      - outside

  escota_db:
    container_name: escota_db
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=devsecret
      - POSTGRES_USER=admin
      - POSTGRES_DB=escota_db
    networks:
      - outside

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - outside

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    env_file:
    - .docker.env
    restart: unless-stopped
    networks:
      - outside

volumes:
  conf:
  html:
  vhost:

networks:
  outside:
