services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: runner
    ports:
      - 3000:3000
    platform: linux/amd64
    env_file:
      - .env.docker
    environment:
      AUTH_KEYCLOAK_ID: ${AUTH_KEYCLOAK_ID}
      AUTH_KEYCLOAK_SECRET: ${AUTH_KEYCLOAK_SECRET}
      AUTH_SECRET: ${AUTH_SECRET}
      PUBLIC_AUTH_KEYCLOAK_ISSUER: https://auth.nexolabs.xyz/realms/Escohotado

      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

      DATABASE_URL: postgresql://admin:devsecret@escota_db:5432/escota_web?schema=public
      PUBLIC_CMS_URL: ${PUBLIC_CMS_URL}
    depends_on:
      - postgres
      - cms

  cms:
    container_name: cms
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: runner
    ports:
      - 3001:3000
    platform: linux/amd64
    env_file:
      - .env.docker
    environment:
      DATABASE_URI: postgresql://admin:devsecret@escota_db:5432/escota_cms
      PAYLOAD_SECRET: YOUR_SECRET_HERE
      NODE_ENV: production


    depends_on:
      - postgres

  postgres:
    container_name: escota_db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=devsecret
      - POSTGRES_USER=admin
      - POSTGRES_DB=escota_web
