services:
  server:
    build:
      context: .
      target: Deploy
    ports:
      - 3000:3000
    platform: linux/amd64
    env_file:
      - ./.env
    environment:
      PUBLIC_AUTH_KEYCLOAK_ID: ${PUBLIC_AUTH_KEYCLOAK_ID}
      PUBLIC_AUTH_KEYCLOAK_SECRET: ${PUBLIC_AUTH_KEYCLOAK_SECRET}
      PUBLIC_AUTH_SECRET: ${PUBLIC_AUTH_SECRET}
      PUBLIC_AUTH_KEYCLOAK_ISSUER: https://auth.nexolabs.xyz/realms/Escohotado

      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      DOMAIN: localhost

      DATABASE_URL: mongodb://admin:devsecret@escota_db:27017/escota_db?authSource=admin
    networks:
      - mongo_net
    depends_on:
      - escota_db

  escota_db:
    image: mongo:4.2.3-bionic
    container_name: escota_db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=escota_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=devsecret
    volumes:
      - ./volumes/mongodb:/data/db
      - ./volumes/configdb:/data/configdb
    networks:
      - mongo_net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:devsecret@escota_db:27017
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - mongo_net
    depends_on:
      - escota_db

networks:
  mongo_net:
    driver: bridge