/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    prices: Price;
    products: Product;
    subscriptions: Subscription;
    media: Media;
    taxonomy: Taxonomy;
    article_pdf: ArticlePdf;
    article_web: ArticleWeb;
    book: Book;
    video: Video;
    permission: Permission;
    'search-results': SearchResult;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      subscription: 'subscriptions';
    };
    prices: {
      product: 'products';
    };
    taxonomy: {
      children: 'taxonomy';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    prices: PricesSelect<false> | PricesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    taxonomy: TaxonomySelect<false> | TaxonomySelect<true>;
    article_pdf: ArticlePdfSelect<false> | ArticlePdfSelect<true>;
    article_web: ArticleWebSelect<false> | ArticleWebSelect<true>;
    book: BookSelect<false> | BookSelect<true>;
    video: VideoSelect<false> | VideoSelect<true>;
    permission: PermissionSelect<false> | PermissionSelect<true>;
    'search-results': SearchResultsSelect<false> | SearchResultsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  name?: string | null;
  roles?: string[];
  subscription?: {
    docs?: (string | Subscription)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  stripeCustomerId?: string | null;
  id: string;
  email: string;
  image?: string | null;
  emailVerified?: string | null;
  accounts?:
    | {
        id?: string | null;
        provider: string;
        providerAccountId: string;
        type: string;
      }[]
    | null;
  sessions?:
    | {
        id?: string | null;
        sessionToken: string;
        expires: string;
      }[]
    | null;
  verificationTokens?:
    | {
        id?: string | null;
        token: string;
        expires: string;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  user: string | User;
  product: string | Product;
  status: 'trialing' | 'active' | 'canceled' | 'incomplete' | 'incomplete_expired' | 'past_due' | 'unpaid' | 'paused';
  created?: string | null;
  currentPeriodStart?: string | null;
  currentPeriodEnd?: string | null;
  endedAt?: string | null;
  cancelAt?: string | null;
  canceledAt?: string | null;
  cancelAtPeriodEnd?: boolean | null;
  trialStart?: string | null;
  trialEnd?: string | null;
  stripeID: string;
  stripePriceID: string;
  stripeCustomerId: string;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  permissions_seeds?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  stripeID: string;
  type?: ('good' | 'service') | null;
  active: boolean;
  name: string;
  description?: string | null;
  images?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  prices?: (string | Price)[] | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  features?:
    | {
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  permissions?: (string | Permission)[] | null;
  permissions_seeds?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices".
 */
export interface Price {
  id: string;
  stripeID: string;
  stripeProductId: string;
  product?: {
    docs?: (string | Product)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  active: boolean;
  description?: string | null;
  unitAmount: number;
  currency: string;
  type: 'one_time' | 'recurring';
  interval?: ('day' | 'week' | 'month' | 'year') | null;
  intervalCount?: number | null;
  trialPeriodDays?: number | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission".
 */
export interface Permission {
  id: string;
  slug: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  title?: string | null;
  rawContent?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy".
 */
export interface Taxonomy {
  id: string;
  selectable?: boolean | null;
  slug: string;
  singular_name: string;
  plural_name?: string | null;
  seed?: string | null;
  parent?: (string | null) | Taxonomy;
  children?: {
    docs?: (string | Taxonomy)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article_pdf".
 */
export interface ArticlePdf {
  id: string;
  permissions?: (string | Permission)[] | null;
  permissions_seeds?: string | null;
  cover: string | Media;
  title?: string | null;
  description?: string | null;
  publishedAt: string;
  categories?: (string | Taxonomy)[] | null;
  seeds?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article_web".
 */
export interface ArticleWeb {
  id: string;
  permissions?: (string | Permission)[] | null;
  permissions_seeds?: string | null;
  cover: string | Media;
  title?: string | null;
  description?: string | null;
  publishedAt: string;
  categories?: (string | Taxonomy)[] | null;
  seeds?: string | null;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content_html?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book".
 */
export interface Book {
  id: string;
  cover: string | Media;
  title?: string | null;
  description?: string | null;
  publishedAt: string;
  categories?: (string | Taxonomy)[] | null;
  seeds?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content_html?: string | null;
  slug: string;
  Ediciones?:
    | {
        link?: string | null;
        variant?: ('audiobook' | 'ebook' | 'book') | null;
        language?: ('es' | 'en') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video".
 */
export interface Video {
  id: string;
  url: string;
  permissions?: (string | Permission)[] | null;
  url_free?: string | null;
  permissions_seeds?: string | null;
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  thumbnailUrl?: string | null;
  title?: string | null;
  description?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-results".
 */
export interface SearchResult {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'video';
        value: string | Video;
      }
    | {
        relationTo: 'article_web';
        value: string | ArticleWeb;
      }
    | {
        relationTo: 'article_pdf';
        value: string | ArticlePdf;
      }
    | {
        relationTo: 'book';
        value: string | Book;
      };
  tags?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'prices';
        value: string | Price;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'taxonomy';
        value: string | Taxonomy;
      } | null)
    | ({
        relationTo: 'article_pdf';
        value: string | ArticlePdf;
      } | null)
    | ({
        relationTo: 'article_web';
        value: string | ArticleWeb;
      } | null)
    | ({
        relationTo: 'book';
        value: string | Book;
      } | null)
    | ({
        relationTo: 'video';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'permission';
        value: string | Permission;
      } | null)
    | ({
        relationTo: 'search-results';
        value: string | SearchResult;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  subscription?: T;
  stripeCustomerId?: T;
  id?: T;
  email?: T;
  image?: T;
  emailVerified?: T;
  accounts?:
    | T
    | {
        id?: T;
        provider?: T;
        providerAccountId?: T;
        type?: T;
      };
  sessions?:
    | T
    | {
        id?: T;
        sessionToken?: T;
        expires?: T;
      };
  verificationTokens?:
    | T
    | {
        id?: T;
        token?: T;
        expires?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices_select".
 */
export interface PricesSelect<T extends boolean = true> {
  stripeID?: T;
  stripeProductId?: T;
  product?: T;
  active?: T;
  description?: T;
  unitAmount?: T;
  currency?: T;
  type?: T;
  interval?: T;
  intervalCount?: T;
  trialPeriodDays?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  stripeID?: T;
  type?: T;
  active?: T;
  name?: T;
  description?: T;
  images?:
    | T
    | {
        url?: T;
        id?: T;
      };
  prices?: T;
  metadata?: T;
  features?:
    | T
    | {
        title?: T;
        id?: T;
      };
  permissions?: T;
  permissions_seeds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  user?: T;
  product?: T;
  status?: T;
  created?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  endedAt?: T;
  cancelAt?: T;
  canceledAt?: T;
  cancelAtPeriodEnd?: T;
  trialStart?: T;
  trialEnd?: T;
  stripeID?: T;
  stripePriceID?: T;
  stripeCustomerId?: T;
  metadata?: T;
  permissions_seeds?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  rawContent?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxonomy_select".
 */
export interface TaxonomySelect<T extends boolean = true> {
  id?: T;
  selectable?: T;
  slug?: T;
  singular_name?: T;
  plural_name?: T;
  seed?: T;
  parent?: T;
  children?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article_pdf_select".
 */
export interface ArticlePdfSelect<T extends boolean = true> {
  permissions?: T;
  permissions_seeds?: T;
  cover?: T;
  title?: T;
  description?: T;
  publishedAt?: T;
  categories?: T;
  seeds?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article_web_select".
 */
export interface ArticleWebSelect<T extends boolean = true> {
  permissions?: T;
  permissions_seeds?: T;
  cover?: T;
  title?: T;
  description?: T;
  publishedAt?: T;
  categories?: T;
  seeds?: T;
  slug?: T;
  content?: T;
  content_html?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "book_select".
 */
export interface BookSelect<T extends boolean = true> {
  cover?: T;
  title?: T;
  description?: T;
  publishedAt?: T;
  categories?: T;
  seeds?: T;
  content?: T;
  content_html?: T;
  slug?: T;
  Ediciones?:
    | T
    | {
        link?: T;
        variant?: T;
        language?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "video_select".
 */
export interface VideoSelect<T extends boolean = true> {
  url?: T;
  permissions?: T;
  url_free?: T;
  permissions_seeds?: T;
  tags?: T;
  thumbnailUrl?: T;
  title?: T;
  description?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permission_select".
 */
export interface PermissionSelect<T extends boolean = true> {
  id?: T;
  slug?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-results_select".
 */
export interface SearchResultsSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}