export { 
    COLLECTION_SLUG_USER,
    COLLECTION_SLUG_ARTICLE_PDF,
    COLLECTION_SLUG_ARTICLE_WEB,
    COLLECTION_SLUG_VIDEO,
    COLLECTION_SLUG_BOOK,
    COLLECTION_SLUG_MEDIA,
    COLLECTION_SLUG_PERMISSION,
    COLLECTION_SLUG_PRICES,
    COLLECTION_SLUG_PRODUCTS,
    COLLECTION_SLUG_QUOTE,
    COLLECTION_SLUG_SUBSCRIPTIONS,
    COLLECTION_SLUG_TAXONOMY,
    COLLECTION_SLUG_UI_BLOCK,
    COLLECTION_SLUG_UI_GRID_CARDS,
    collectionsContentsSlugs,
    collectionsSlugs
 } from './payload/collectionsSlugs'

 export {
    generateDetailHref
 } from './payload/routesGenerator'