version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules:delegated
    command: sleep infinity
    ports:
      - "3000:3000"
      - "6006:6006"
    environment:
      - DATABASE_URL=postgresql://admin:devsecret@localhost/escota-db
      - NODE_ENV=development
    env_file:
      - ../.env
    depends_on:
      - escota_db
    networks:
      - outside

  stripe_webhooks:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "stripe login --api-key \${STRIPE_API_KEY:-} &&
      echo '====== WEBHOOK SETUP ======' &&
      echo 'Stripe webhook está escuchando eventos...' &&
      echo 'Copia el webhook signing secret a continuación y configúralo en tu archivo .env como STRIPE_WEBHOOK_SECRET:' &&
      stripe listen --forward-to app:3000/api/stripe/webhooks"
    environment:
      - STRIPE_API_KEY=${STRIPE_API_KEY:-}
    env_file:
      - ../.env
    volumes:
      - ../.stripe:/root/.config/stripe
    networks:
      - outside
    depends_on:
      - app

  escota_db:
    container_name: escota_db
    image: postgres:17-alpine
    restart: always
    volumes:
      - ../.docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=devsecret
      - POSTGRES_USER=escota
      - POSTGRES_DB=escota_db
    ports:
      - "5432:5432"
    networks:
      - outside

volumes:
  postgres-data:
  node_modules:
networks:
  outside:
