name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    tags:
      - "v*"
    branches:
      - main
    paths:
      - "packages/gaudi/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install -g pnpm

      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        env:
          STORYBOOK_FIGMA_ACCESS_TOKEN: ${{ secrets.STORYBOOK_FIGMA_ACCESS_TOKEN }}
          # Aseguramos que no se ejecuta Chromatic automáticamente
          SKIP_CHROMATIC: "true"
        with:
          install_command: pnpm install --no-frozen-lockfile
          build_command: cd apps/server && pnpm build-storybook
          path: apps/server/storybook-static
          checkout: false
