name: Publish Package

on:
  push:
    branches:
      - main # O la rama que uses para publicar

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com/'

    - name: Configure .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

    - name: Install dependencies
      run: yarn install

    - name: Build package
      run: yarn build

    - name: Publish package
      run: yarn publish --non-interactive
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
